Repository chingu-voyages/v8-bears-team-15, pull requests merged in 2019-04, with the labels that each got.

#1 create app server scaffold with database connection
  server/config/config.js
  server/index.js
  server/package.json
  server/start.js
  server/yarn-error.log
  server/yarn.lock
Labels: enhancement

#3 create user model and minor modifications
  server/.eslintrc.js
  server/.gitignore
  server/index.js
  server/models/User.js
  server/package.json
  server/yarn.lock
Labels: enhancement

#4 Chore: setup-server-side-testing-environment
  server/.babelrc
  server/.eslintrc.js
  server/.gitignore
  server/index.js
  server/package.json
  server/routes/index.js
  server/test/app.test.js
  server/yarn-error.log
  server/yarn.lock
Labels: enhancement

#7 fix server start
  .gitignore
  package.json
  server/auth/facebook.js
  server/auth/google.js
  server/auth/linkedIn.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/src/auth/facebook.js
  server/src/auth/google.js
  server/src/auth/linkedIn.js
  server/src/auth/sessions.js
  server/src/config/config.js
  server/src/helper/logger.js
  server/src/index.js
  server/src/models/User.js
  server/src/routes/index.js
  server/src/test/app.test.js
  server/start.js
  yarn.lock
Labels: bug

#8 Feature/landing page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/Home/HomeActions.js
  client/src/actions/User/UserActions.js
  client/src/actions/actionConstants.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Home/Home.css
  client/src/components/Home/Home.js
  client/src/components/Modal/Modal.css
  client/src/components/Modal/Modal.js
  client/src/components/Pop/Pop.css
  client/src/components/Pop/Pop.js
  client/src/images/auth/facebook.png
  client/src/images/auth/google_icon.png
  client/src/images/auth/linkedin.png
  client/src/images/jb_logo_white.svg
  client/src/images/jobbatical_logo_blue.svg
  client/src/images/social-media/facebook.png
  client/src/images/social-media/googleplus.png
  client/src/images/social-media/instagram.png
  client/src/images/social-media/linkedin.png
  client/src/images/social-media/twitter.png
  client/src/index.js
  client/src/middleware/logger.js
  client/src/reducers/Home/homeReducers.js
  client/src/reducers/User/userReducer.js
  client/src/reducers/rootReducer.js
  client/src/store/configureStore.js
  client/yarn.lock
  server/.eslintignore
  server/.eslintrc.js
  server/controllers/AuthenticationController.js
  server/package.json
  server/src/auth/google.js
  server/src/auth/jwt.js
  server/src/auth/linkedIn.js
  server/src/auth/local.js
  server/src/auth/sessions.js
  server/src/config/config.js
  server/src/index.js
  server/src/models/User.js
  server/src/routes/index.js
  server/yarn.lock
Labels: enhancement, help wanted

#11 Feature/edit profile
  client/src/components/Dashboard/CV/About/About.css
  client/src/components/Dashboard/CV/About/About.js
  client/src/components/Dashboard/CV/AddExperience/AddExperience.css
  client/src/components/Dashboard/CV/AddExperience/AddExperience.js
  client/src/components/Dashboard/CV/Experience/Experience.css
  client/src/components/Dashboard/CV/Experience/Experience.js
  client/src/components/Dashboard/CV/Language/Language.css
  client/src/components/Dashboard/CV/Language/Language.js
  client/src/components/Dashboard/CV/Links/Links.css
  client/src/components/Dashboard/CV/Links/Links.js
  client/src/components/Dashboard/CV/Profile/Profile.css
  client/src/components/Dashboard/CV/Profile/Profile.js
  client/src/components/Dashboard/CV/Skills/Skills.css
  client/src/components/Dashboard/CV/Skills/Skills.js
Labels: enhancement

#16 Feature/seed data
  server/.eslintignore
  server/controllers/AuthenticationController.js
  server/package.json
  server/seed.js
  server/seeds/companies.js
  server/seeds/users.js
  server/src/auth/facebook.js
  server/src/auth/jwt.js
  server/src/auth/local.js
  server/src/config/config.js
  server/src/index.js
  server/yarn.lock
Labels: good first issue
